from pathlib import Path
import math
import re
import struct
import wave


ROOT = Path(".")


# ============================================================
# 1. Generate native picker tick sound
# ============================================================

raw_dir = (
    ROOT
    / "android"
    / "app"
    / "src"
    / "main"
    / "res"
    / "raw"
)

raw_dir.mkdir(
    parents=True,
    exist_ok=True,
)

wav_path = raw_dir / "liv_picker_tick.wav"

SAMPLE_RATE = 44100
DURATION = 0.032
FRAME_COUNT = int(SAMPLE_RATE * DURATION)

with wave.open(str(wav_path), "wb") as wav:
    wav.setnchannels(1)
    wav.setsampwidth(2)
    wav.setframerate(SAMPLE_RATE)

    frames = bytearray()

    for i in range(FRAME_COUNT):
        t = i / SAMPLE_RATE

        attack = min(1.0, t / 0.0012)
        decay = math.exp(-t * 120.0)

        tone = (
            0.55 * math.sin(
                2.0 * math.pi * 2900.0 * t
            )
            +
            0.20 * math.sin(
                2.0 * math.pi * 5200.0 * t
            )
        )

        sample = tone * attack * decay

        sample = max(
            -1.0,
            min(1.0, sample)
        )

        frames.extend(
            struct.pack(
                "<h",
                int(sample * 32767)
            )
        )

    wav.writeframes(frames)

print(f"Created picker sound: {wav_path}")


# ============================================================
# 2. Find MainActivity.kt
# ============================================================

kotlin_root = (
    ROOT
    / "android"
    / "app"
    / "src"
    / "main"
    / "kotlin"
)

main_files = list(
    kotlin_root.rglob("MainActivity.kt")
)

if not main_files:
    raise SystemExit(
        "ERROR: MainActivity.kt was not generated by Flutter."
    )

main_activity = main_files[0]

original = main_activity.read_text(
    encoding="utf-8"
)


# ============================================================
# 3. Detect package
# ============================================================

package_match = re.search(
    r"^\s*package\s+([^\s]+)",
    original,
    re.MULTILINE,
)

if not package_match:
    raise SystemExit(
        "ERROR: Could not determine MainActivity package."
    )

package_name = package_match.group(1).strip()


# ============================================================
# 4. Install native Android feedback bridge
# ============================================================

native_activity = f"""package {package_name}

import android.content.Context
import android.media.AudioAttributes
import android.media.AudioManager
import android.media.SoundPool
import android.media.ToneGenerator
import android.os.Build
import android.os.Bundle
import android.os.VibrationEffect
import android.os.Vibrator
import android.os.VibratorManager

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel


class MainActivity : FlutterActivity() {{

    companion object {{
        private const val CHANNEL = "liv.feedback"
    }}

    private var soundPool: SoundPool? = null
    private var tickSoundId: Int = 0
    private var soundLoaded = false
    private var toneGenerator: ToneGenerator? = null


    override fun onCreate(
        savedInstanceState: Bundle?
    ) {{
        super.onCreate(savedInstanceState)

        val audioAttributes =
            AudioAttributes.Builder()
                .setUsage(
                    AudioAttributes.USAGE_ASSISTANCE_SONIFICATION
                )
                .setContentType(
                    AudioAttributes.CONTENT_TYPE_SONIFICATION
                )
                .build()

        soundPool =
            SoundPool.Builder()
                .setMaxStreams(4)
                .setAudioAttributes(audioAttributes)
                .build()

        soundPool?.setOnLoadCompleteListener {{
            _,
            sampleId,
            status ->

            if (
                status == 0 &&
                sampleId == tickSoundId
            ) {{
                soundLoaded = true
            }}
        }}

        tickSoundId =
            soundPool?.load(
                this,
                R.raw.liv_picker_tick,
                1
            ) ?: 0

        toneGenerator =
            try {{
                ToneGenerator(
                    AudioManager.STREAM_MUSIC,
                    35
                )
            }} catch (
                _: Exception
            ) {{
                null
            }}
    }}


    override fun configureFlutterEngine(
        flutterEngine: FlutterEngine
    ) {{
        super.configureFlutterEngine(flutterEngine)

        MethodChannel(
            flutterEngine
                .dartExecutor
                .binaryMessenger,
            CHANNEL
        ).setMethodCallHandler {{
            call,
            result ->

            when (call.method) {{

                "tick" -> {{
                    playTickSound()
                    playTickHaptic()

                    result.success(null)
                }}

                else -> {
                    result.notImplemented()
                }
            }}
        }}
    }}


    private fun playTickSound() {{

        if (
            soundLoaded &&
            tickSoundId != 0
        ) {{

            soundPool?.play(
                tickSoundId,
                0.34f,
                0.34f,
                10,
                0,
                1.0f
            )

            return
        }}

        try {{
            toneGenerator?.startTone(
                ToneGenerator.TONE_PROP_BEEP,
                25
            )
        }} catch (
            _: Exception
        ) {{}}
    }}


    private fun playTickHaptic() {{

        try {{

            val vibrator: Vibrator =
                if (
                    Build.VERSION.SDK_INT >=
                    Build.VERSION_CODES.S
                ) {{

                    getSystemService(
                        VibratorManager::class.java
                    ).defaultVibrator

                }} else {{

                    @Suppress("DEPRECATION")
                    getSystemService(
                        Context.VIBRATOR_SERVICE
                    ) as Vibrator
                }}

            if (!vibrator.hasVibrator()) {{
                return
            }}


            if (
                Build.VERSION.SDK_INT >=
                Build.VERSION_CODES.S
            ) {{

                val support =
                    vibrator.areEffectsSupported(
                        VibrationEffect.EFFECT_TICK
                    )

                if (
                    support.isNotEmpty() &&
                    support[0] ==
                    Vibrator.VIBRATION_EFFECT_SUPPORT_YES
                ) {{

                    vibrator.vibrate(
                        VibrationEffect.createPredefined(
                            VibrationEffect.EFFECT_TICK
                        )
                    )

                    return
                }}
            }}


            if (
                Build.VERSION.SDK_INT >=
                Build.VERSION_CODES.Q
            ) {{

                vibrator.vibrate(
                    VibrationEffect.createPredefined(
                        VibrationEffect.EFFECT_TICK
                    )
                )

                return
            }}


            if (
                Build.VERSION.SDK_INT >=
                Build.VERSION_CODES.O
            ) {{

                vibrator.vibrate(
                    VibrationEffect.createOneShot(
                        8L,
                        70
                    )
                )

                return
            }}


            @Suppress("DEPRECATION")
            vibrator.vibrate(8L)

        }} catch (
            _: Exception
        ) {{}}
    }}


    override fun onDestroy() {{

        try {{
            soundPool?.release()
        }} catch (
            _: Exception
        ) {{}}

        soundPool = null

        try {{
            toneGenerator?.release()
        }} catch (
            _: Exception
        ) {{}}

        toneGenerator = null

        super.onDestroy()
    }}
}}
"""


main_activity.write_text(
    native_activity,
    encoding="utf-8"
)

print(
    f"Patched native Android feedback: {main_activity}"
)


# ============================================================
# 5. Patch onboarding_screen.dart ROBUSTLY
# ============================================================

onboarding = (
    ROOT
    / "lib"
    / "screens"
    / "onboarding_screen.dart"
)

if not onboarding.exists():
    raise SystemExit(
        "ERROR: onboarding_screen.dart does not exist."
    )

text = onboarding.read_text(
    encoding="utf-8"
)


# ------------------------------------------------------------
# 5A. Add AudioService import
# ------------------------------------------------------------

if (
    "services/audio_service.dart"
    not in text
):

    flutter_import = (
        "import 'package:flutter/material.dart';"
    )

    if flutter_import in text:

        text = text.replace(
            flutter_import,
            flutter_import
            + "\n"
            + "import '../services/audio_service.dart';",
            1,
        )

    else:

        text = (
            "import '../services/audio_service.dart';\n"
            + text
        )


# ------------------------------------------------------------
# 5B. Remove duplicate old age feedback
# ------------------------------------------------------------

age_method_pattern = re.compile(
    r"""
    (\s*)
    void\s+_tickAgeItem\s*\(\s*\)
    \s*\{
    .*?
    \n\s*\}
    """,
    re.DOTALL | re.VERBOSE,
)

age_method_match = age_method_pattern.search(text)

new_age_method = """
  void _tickAgeItem() {
    AudioService.instance.tick();
  }
"""

if age_method_match:

    indentation = age_method_match.group(1)

    replacement = (
        indentation
        + "void _tickAgeItem() {\n"
        + indentation
        + "  AudioService.instance.tick();\n"
        + indentation
        + "}\n"
    )

    text = (
        text[:age_method_match.start()]
        + replacement
        + text[age_method_match.end():]
    )

else:

    # Insert before _tick if available.
    tick_match = re.search(
        r"\n\s*Future<void>\s+_tick\s*\(",
        text
    )

    if tick_match:

        insert_at = tick_match.start()

        text = (
            text[:insert_at]
            + "\n"
            + new_age_method
            + text[insert_at:]
        )

    else:

        raise SystemExit(
            "ERROR: Could not find _tickAgeItem or _tick in onboarding_screen.dart"
        )


# ------------------------------------------------------------
# 5C. Find the AGE picker callback
# ------------------------------------------------------------

callback_pattern = re.compile(
    r"""
    onSelectedItemChanged
    \s*:\s*
    \(
        \s*([A-Za-z_][A-Za-z0-9_]*)\s*
    \)
    \s*
    (?:
        async\s*
    )?
    \{
        .*?
    \}
    \s*,
    """,
    re.DOTALL | re.VERBOSE,
)


matches = list(
    callback_pattern.finditer(text)
)


if not matches:

    raise SystemExit(
        "ERROR: Could not find any onSelectedItemChanged callback."
    )


# Prefer the callback containing age assignment.

age_callback = None

for match in matches:

    block = match.group(0)

    if (
        "_age" in block
        and "+ 12" in block
    ):
        age_callback = match
        break


if age_callback is None:

    raise SystemExit(
        "ERROR: Found picker callbacks, "
        "but none matched the expected age assignment."
    )


callback_text = age_callback.group(0)

index_var = age_callback.group(1)


new_callback = f"""onSelectedItemChanged: ({index_var}) {{
                  final nextAge = {index_var} + 12;

                  if (nextAge == _age) {{
                    return;
                  }}

                  setState(() {{
                    _age = nextAge;
                  }});

                  _tickAgeItem();
                }},
"""


text = (
    text[:age_callback.start()]
    + new_callback
    + text[age_callback.end():]
)


# ------------------------------------------------------------
# 5D. Ensure picker uses magnifier
# ------------------------------------------------------------

if (
    "useMagnifier: true"
    not in text
):

    # Only patch the first CupertinoPicker-like itemExtent.
    item_match = re.search(
        r"itemExtent\s*:\s*40\s*,",
        text
    )

    if item_match:

        replacement = """
itemExtent: 44,
                diameterRatio: 1.2,
                squeeze: 1.05,
                useMagnifier: true,
                magnification: 1.28,
"""

        text = (
            text[:item_match.start()]
            + replacement
            + text[item_match.end():]
        )


# ------------------------------------------------------------
# 5E. Write onboarding
# ------------------------------------------------------------

onboarding.write_text(
    text,
    encoding="utf-8"
)

print(
    f"Patched onboarding: {onboarding}"
)


# ============================================================
# 6. HARD VERIFICATION
# ============================================================

final_text = onboarding.read_text(
    encoding="utf-8"
)


errors = []


# AudioService import
if (
    "services/audio_service.dart"
    not in final_text
):
    errors.append(
        "AudioService import is missing."
    )


# Age helper
if (
    "void _tickAgeItem()" not in final_text
):
    errors.append(
        "_tickAgeItem() is missing."
    )


# Native call
if (
    "AudioService.instance.tick();" not in final_text
):
    errors.append(
        "AudioService.instance.tick() is missing."
    )


# Picker callback
if (
    "onSelectedItemChanged" not in final_text
):
    errors.append(
        "onSelectedItemChanged is missing."
    )


# Age assignment
if not re.search(
    r"_age\s*=\s*[A-Za-z_][A-Za-z0-9_]*\s*\+\s*12",
    final_text
):
    errors.append(
        "Age assignment inside picker is missing."
    )


# Picker feedback call
if (
    "_tickAgeItem();" not in final_text
):
    errors.append(
        "_tickAgeItem() is not called by the picker."
    )


# Native bridge
native_text = main_activity.read_text(
    encoding="utf-8"
)

if (
    'private const val CHANNEL = "liv.feedback"'
    not in native_text
):
    errors.append(
        "Native MethodChannel is missing."
    )


if (
    "SoundPool" not in native_text
):
    errors.append(
        "SoundPool is missing."
    )


if (
    "EFFECT_TICK" not in native_text
):
    errors.append(
        "Native EFFECT_TICK haptic is missing."
    )


# Sound
if not wav_path.exists():
    errors.append(
        "Picker WAV file was not generated."
    )


# Permission
manifest = (
    ROOT
    / "android"
    / "app"
    / "src"
    / "main"
    / "AndroidManifest.xml"
)

if manifest.exists():

    manifest_text = manifest.read_text(
        encoding="utf-8"
    )

    if (
        "android.permission.VIBRATE"
        not in manifest_text
    ):
        errors.append(
            "VIBRATE permission is missing."
        )

else:

    errors.append(
        "AndroidManifest.xml is missing."
    )


# ============================================================
# 7. FAIL THE BUILD IF ANYTHING IS WRONG
# ============================================================

if errors:

    print("")
    print("========================================")
    print("LIV FEEDBACK PATCH FAILED")
    print("========================================")

    for error in errors:
        print("ERROR:", error)

    print("")
    print(
        "The APK will NOT be built because "
        "native picker feedback is not verified."
    )

    raise SystemExit(1)


# ============================================================
# SUCCESS
# ============================================================

print("")
print("========================================")
print("LIV FEEDBACK PATCH VERIFIED")
print("========================================")
print("")
print("✓ Picker sound generated")
print("✓ SoundPool installed")
print("✓ Native MethodChannel installed")
print("✓ Native haptic installed")
print("✓ VIBRATE permission detected")
print("✓ AudioService connected")
print("✓ Age picker callback detected")
print("✓ Age picker calls _tickAgeItem()")
print("✓ _tickAgeItem() calls AudioService.instance.tick()")
print("")
print("Native picker feedback is ready for APK build.")
print("========================================")